name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm gcc-multilib grub-pc-bin xorriso mtools

      - name: Build project
        run: make

      - name: Build ISO
        run: make iso

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vos9-os-build
          path: |
            build/*.bin
            build/*.o
            build/*.img
            build/*.iso